name: ptolemay
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # router
  go_router: ^3.1.0

  # State management
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3

  # injection
  get_it: ^7.2.0

  # Network
  dio: ^4.0.6
  pretty_dio_logger: ^1.1.1
  retrofit: '>=3.0.0 <4.0.0'
  chuck_interceptor: ^1.0.1
  geolocator: ^9.0.1

  # Data
  either_dart: ^0.1.4
 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_gen_runner: ^4.1.6
  build_runner: ^2.1.10
  retrofit_generator: any


flutter_gen:
  output: lib/gen/
  lineLength: 120

  integrations:
    flutter_svg: true
  colors:
    enabled: true
    inputs:
      - assets/color/colors.xml  

flutter:
  uses-material-design: true

  # assets:
    

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
